### ISSUE TITLE
Change font style and size

### ISSUE THREAD

**Issue by mxssl** [zwbetz-gh/minimal-bootstrap-hugo-theme#1]
Hi!

Please consider adding an ability to change font and font size through `config.toml` file.

**Comment by zwbetz-gh** [comment]
Hi @mxssl,

Some folks may want a different base font, then a different code snippet font, then a different quote font, etc. etc. So this would make the `config.toml` overly-complex. 

Changing font and font size are better done by overriding the theme. As an example, say you wanted to use Roboto, Google's Font. 

1. Copy `themes/minimal-bootstrap-hugo-theme/layouts/partials/head.html` and paste it at `layouts/partials/head.html`
1. Add this line to `layouts/partials/head.html`
    ```
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,700,700i" 
    rel="stylesheet">
    ```
1. Copy `themes/minimal-bootstrap-hugo-theme/layouts/partials/style.html` and paste it at `layouts/partials/style.html`
1. Add these lines to `layouts/partials/style.html`
    ```
    body {
      font-family: 'Roboto', sans-serif;
      font-size: 14px;
    }
    ```

**Note:** If you change the font size to anything other than 16px (which is the bootstrap v4 default), then you'll need to update the CSS for navbar anchor padding. See https://github.com/zwbetz-gh/minimal-bootstrap-hugo-theme/blob/master/layouts/partials/style.html#L13

**Comment by mxssl** [comment]
Thanks for clarifications!
