### ISSUE TITLE
bootstrap.min.css 404

### ISSUE THREAD

**Issue by QCU87Z** [zwbetz-gh/minimal-bootstrap-hugo-theme#11]
**Describe the bug**
CSS doesn't load when website is accessed from a different client (i.e. not localhost)
If I look at the page with chrome dev tools I see the following
```
GET http://localhost:1313/css/bootstrap.min.css net::ERR_CONNECTION_REFUSED
```

**To Reproduce**
1. Copy exampleSite into the root of the sight
2. Override config.toml
3. hugo server --bind 0.0.0.0

**Expected behavior**
Website to load with correct CSS applied

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 with latest Chrome 80.0

**Additional context**
I dont get this issue if I browser to the page from the same computer that hugo is running on.

**Comment by zwbetz-gh** [comment]
It sounds like you're running the site on your Desktop, but then want to access it from a different device. Is that correct?

If so, then follow the steps in this link and specify the `--baseURL` flag. Then let me know how it goes. 

https://zwbetz.com/preview-your-site-from-any-device-on-your-network-with-these-hugo-server-options/

**Comment by QCU87Z** [comment]
Sorry about the delay that is exactly what I needed thanks.
