### ISSUE TITLE
How to config pagination of the posts?

### ISSUE THREAD

**Issue by nkcoder** [zwbetz-gh/minimal-bootstrap-hugo-theme#12]
Is there a configuration for pagination of the posts? Thanks.

**Comment by zwbetz-gh** [comment]
Hi, no there is not. But you can easily add it. See the [hugo docs on pagination](https://gohugo.io/templates/pagination/#readout). Then you'll want to put your pagination code at https://github.com/zwbetz-gh/minimal-bootstrap-hugo-theme/blob/master/layouts/index.html
