### ISSUE TITLE
date and tag are not displayed on the post page

### ISSUE THREAD

**Issue by dongruixiao** [zwbetz-gh/minimal-bootstrap-hugo-theme#19]
**Describe the bug**
date and tag are not displayed on the post page

**To Reproduce**

**Expected behavior**
see screenshots

**Screenshots**
yours
![image](https://user-images.githubusercontent.com/16684015/166109786-47186438-89c0-468e-b67e-ea438b5f028a.png)
and mine
![image](https://user-images.githubusercontent.com/16684015/166109823-c19948da-20c3-457a-9149-6d9724a3b6e2.png)

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser: chrome/safari

**Smartphone (please complete the following information):**

**Additional context**
can u help me? tks

**Comment by dongruixiao** [comment]
ok, i got it, i should rename  my folder from `posts` to `post`

**Comment by zwbetz-gh** [comment]
Glad to hear you resolved it.
