### ISSUE TITLE
Error while building template.

### ISSUE THREAD

**Issue by dz-s** [zwbetz-gh/minimal-bootstrap-hugo-theme#2]
**Describe the bug**
If you try `hugo server -D` with this template, you will get an error (below).

**To Reproduce**

Step by step following https://gohugo.io/getting-started/quick-start/ (but with this theme)

**Expected behavior**
Build successful

**Screenshots**
![image](https://user-images.githubusercontent.com/27350480/51784446-dd4b0d00-2159-11e9-9db7-7d94b41d64ba.png)

**Desktop (please complete the following information):**
 - OS: 
Manjaro Linux
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=18.0.2

- Hugo:
Hugo Static Site Generator v0.54-DEV linux/amd64

- Golang:
go version go1.11.4 linux/amd64

**Comment by zwbetz-gh** [comment]
Fixed in https://github.com/zwbetz-gh/minimal-bootstrap-hugo-theme/pull/3
