### ISSUE TITLE
Analytics Partial

### ISSUE THREAD

**Issue by FelixZett** [zwbetz-gh/minimal-bootstrap-hugo-theme#4]
Hey there,
I really like your theme but I found no practical way of adding analytics code like Google Analytics or similar. Is there a layout partial which can be overridden for this purpose?
With regards, 
Felix

**Comment by zwbetz-gh** [comment]
Hi @FelixZett. 
Google Analytics is already supported. You can see this if you take a look at the example [`config.toml`](https://github.com/zwbetz-gh/minimal-bootstrap-hugo-theme/blob/master/exampleSite/config.toml).

There are many params in that file, but really this is all you'll need in your own `config.toml`
```toml
[params]
  googleAnalytics = "UA-123456789-1"
```

**Comment by FelixZett** [comment]
Thanks @zwbetz-gh,
please excuse my bad use of google analytics as example. I was refering to analytics services that uses similar methods like google analytics, but not the tool itself.

**Comment by zwbetz-gh** [comment]
Did you have a particular example in mind?

**Comment by FelixZett** [comment]
Sure, Matomo (formerly Piwik) is an open source analytics. The implementation is similar to Google.
https://matomo.org/docs/installation/#install-the-javascript-tracking-tag
Most themes have some kind of layout partial to add analytics.

**Comment by zwbetz-gh** [comment]
Using your Matomo example, their docs say to insert the relevant JS into the `<head>` element. So you can override this theme's head partial with your custom changes. Here's how to do that:

(1) Copy file
```
/your-site/themes/minimal-bootstrap-hugo-theme/layouts/partials/head.html
```
(2) Paste that file to 
```
/your-site/layouts/partials/head.html
```
(3) Put the Matomo JS into the new head partial you created. Hugo will then use the new partial when building your site

**Comment by FelixZett** [comment]
Thank you very much. That should do the trick.
