### ISSUE TITLE
 help me.

### ISSUE THREAD

**Issue by 1078503** [zwbetz-gh/minimal-bootstrap-hugo-theme#5]
1.  I can't make a page navigation, I hope you can update the theme. 

2. There is also a button that returns to the top.

Thanks.

**Comment by zwbetz-gh** [comment]
For point (1), I cannot help you, unless you give more info. And be sure to read the example [`config.toml`](https://github.com/zwbetz-gh/minimal-bootstrap-hugo-theme/blob/master/exampleSite/config.toml). 

For point (2), this is something you can add yourself by overriding the theme.
