### ISSUE TITLE
Click on tag doesn't filter by that tag

### ISSUE THREAD

**Issue by kevinykuo** [zwbetz-gh/minimal-bootstrap-hugo-theme#6]
reprex: go to https://minimal-bootstrap-hugo-theme.netlify.com/tags/command-line/ and click on any of the tags

**Comment by zwbetz-gh** [comment]
Good find. This issue is affecting some of my other themes as well. It's a side effect of changes I made to address hugo 0.57.0 changes. 

Once back at my laptop I'll put in a fix.

**Comment by zwbetz-gh** [comment]
Fixed in https://github.com/zwbetz-gh/minimal-bootstrap-hugo-theme/commit/55e1a661773e78751c9b66a60ecbb507e5bd214c
