### ISSUE TITLE
Home entry doesn't work as expected (support request)

### ISSUE THREAD

**Issue by donho** [zwbetz-gh/minimal-bootstrap-hugo-theme#9]
(Sorry, it's rather a support request)

I try to have the "Home entry" to point to a static markdown file, so the root of site will point to content/index.html, also the first menu entry `Home`.

My home markdown file is named `index.md` and under my `content folder`. Here is my menu in config.toml looks like: 
```
[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Download"
    url = "/downloads/"
    weight = 3
```
However, Hugo doesn't generate Home correctly, and either the other entries.

Could you enlight me what I'm missing please?

Nice and efficient theme BTW!

**Comment by zwbetz-gh** [comment]
You need to rename

    content/index.md

To be

    content/_index.md

Which will make that page a branch bundle (what you want) instead of a leaf bundle.

**Comment by donho** [comment]
Hmm... I've tried `content/_index.md` : 
hugo generates an empty `index.html` only with "Home" title inside, and all the content in `content/_index.md` is ignored.
Here is the content in `content/_index.md` :
```
---
title: "About"
type: docs
---
**W**in**GUp** is a **G**eneric **Up**dater running under **Win**dows environment.
The aim of WinGUp is to provide a ready to use and configurable updater which downloads a update package then installs it.
By using cURL library and TinyXml module, GUP is capable to deal with http protocol and process XML data.
...
```
_index.md is just ignored.

**Comment by zwbetz-gh** [comment]
On second thought, you will also need to override the homepage template https://github.com/zwbetz-gh/minimal-bootstrap-hugo-theme/blob/master/layouts/index.html

For example give it contents such as

```
{{ define "main" }}

<h1>{{ .Title }}</h1>

{{ .Content }}

{{ end }}
```

Then it will pull from your `content/_index.md`

**Comment by donho** [comment]
@zwbetz-gh 
It works and you just made my night!
Thank you very much!
